 Define environments
environments:
  - name: Test-env

# Define agents
agents:
  - name: admin
    resources: [windows]
    environment_variables:
      JAVA_HOME: "C:\\Program Files\\Java\\jdk-11"
    hostname: 127.0.0.1
    operating_system: Windows 10
    agent_state: Idle
    free_space: "857.68 GB"
    environments: [Test-env]

# Define pipelines
pipelines:
  - name: MyPipeline
    group: myfirstpipeline  # Group name
    materials:
      git:
        url: https://github.com/htetgit/My_Demo.git
        branch: main
    stages:
      - name: Build
        jobs:
          - name: Compile
            agent: admin
            tasks:
              - exec: mvn clean compile
      - name: Test
        jobs:
          - name: UnitTest
            agent: admin
            tasks:
              - exec: mvn test
