format_version: 3
pipelines:
  Demo-App:
    group: myFirstpipeline
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/htetgit/My_Demo.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - App-Stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          App-Job:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - clean
                - compile
                command: mvn
                run_if: passed
