# Use a base image with a minimal Linux distribution
FROM alpine:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the application code into the container
COPY . /app

# Define the command to run when the container starts
CMD ["./hello_world.sh"]
